# Copy of: https://github.com/dotnet/runtime/blob/main/.github/ISSUE_TEMPLATE/01_bug_report.yml
name: ❗ Bug Report
description: Create a report to help us improve.
title: "[Bug]: "
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        We welcome bug reports! This template will help us gather the information we need to start the triage process.
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please share a clear and concise description of the problem.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it.

        We will close this issue if:
        - We are not able to reproduce the behavior you're reporting.
        - The issue is a duplicate of an existing issue.
        - The behavior you're reporting is by design.
      placeholder: Minimal Reproduction
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Provide a description of the expected behavior.
      placeholder: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior. If applicable please include any error messages, exception stacktraces or memory dumps.
      placeholder: Actual behavior
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Please provide more information about the platform configuration:
          * Architecture: x64, x86, ARM, ARM64, RISC...
          * Compiler: gcc, msvc...
          * Compiler flags
          * Hardware: PC, ESP32, ATMEL...
          * Operational System: Windows, Linux, FreeRTOS...
      placeholder: Configuration
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: |
        If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
      placeholder: Other information
    validations:
      required: false