name: build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'lib/**'
      - 'test/**'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_float:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Latest CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: Install Sonar
      uses: sonarsource/sonarcloud-github-c-cpp@v1

    - name: CMake Generate
      shell: pwsh
      run: .\project.ps1 generate float

    - name: CMake Build with Sonar
      shell: pwsh
      run: build-wrapper-win-x86-64.exe --out-dir build_wrapper_output pwsh.exe .\project.ps1 build

    - name: Run Tests
      run: .\project.ps1 test

    - name: Run Sonar Scanner
      run: sonar-scanner --define sonar.token=${{secrets.SONARCLOUD_TOKEN}} --define sonar.organization=${{secrets.SONARCLOUD_ORGANIZATION}}

  build_double:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Get Latest CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: CMake Generate
      shell: pwsh
      run: .\project.ps1 generate double

    - name: CMake Build with Sonar
      shell: pwsh
      run: .\project.ps1 build

    - name: Run Tests
      run: .\project.ps1 test
