name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        type: [double, float]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: CMake Generate
      shell: pwsh
      run: .\project.ps1 generate ${{matrix.type}}

    - name: CMake Build
      shell: pwsh
      run: .\project.ps1 build

    - name: Run Tests
      run: .\project.ps1 test

  release:
    runs-on: windows-2022
    needs: [build]
    permissions:
      contents: write

    env:
      ZIP_NAME: iot-lib-formulas.${{github.ref_name}}.zip

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create Zip
      shell: pwsh
      run: |
        $compress = @{
          Path = "lib\", "CMakeLists.txt", "Kconfig"
          CompressionLevel = "Optimal"
          DestinationPath = $Env:ZIP_NAME
        }
        Compress-Archive @compress

    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "${{env.ZIP_NAME}}"
        makeLatest: true
        name: IoT Lib Formulas ${{github.ref_name}}
        removeArtifacts: false
        replacesArtifacts: true
