name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        type: [double, float]

    steps:
    - uses: actions/checkout@v4

    - name: Get CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: CMake Generate
      shell: pwsh
      run: .\project.ps1 generate ${{matrix.type}}

    - name: CMake Build
      shell: pwsh
      run: .\project.ps1 build

    - name: Run Tests
      run: .\project.ps1 test

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write

    env:
      ZIP_NAME: iot-lib-formulas.${{github.ref_name}}.zip

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Zip
      shell: pwsh
      run: |
        mkdir iot-lib-formulas
        cp -r lib iot-lib-formulas
        cp CMakeLists.txt iot-lib-formulas
        cp Kconfig iot-lib-formulas
        cp LICENSE iot-lib-formulas
        zip -r ${{env.ZIP_NAME}} iot-lib-formulas
        rm -r iot-lib-formulas

    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "${{env.ZIP_NAME}}"
        generateReleaseNotes: true
        makeLatest: true
        name: IoT Lib Formulas ${{github.ref_name}}
        removeArtifacts: false
        replacesArtifacts: true
